---
title: "Computational Biology Projects"
author: "Ely P. Remes"
date: "2024-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Found here are links related to in class assignments completed during the Spring 2024 semester.


Assignment 1: [24_Jan_2024](Homework_02.html)   

     This first assignment was to understand how to create and add webpages using a Github Repository.


Assignment 2: [31_Jan_2024](Homework_03.html)

    The aim of the assignment was to gain practice working with regular expressions to manipulate untidy data into a consistent form.


Assignment 3: [7_Feb_2024](Homework_04.html)

    Here work was done to gain experience working with atomic vectors and different ways to manipulate them.
    
    
Assignment 4: [14_Feb_2024](Homework_05.html)


     Work was Performed to better understand how to manipulate data frames and matrices.


Assignment 5: [21_Feb_2024](Homework_06.html)
    
    
    The object of this assignment was to better understand how to analyze data using tools created in R.  
    
    
Assignment 6: [28_Feb_2024](Homework_07.html)

    Creation and analysis of data derived from a given dataset. The other option here was to use data from one own's lab. Unfortunately, I have none.
    

Assignment 8: [28_Mar_2024](Homework_09.html)

    Generation of functions to create a random dataset when given a sample size, standard deviation, and mean with the ability to have variable treatments. 